---
label: Services
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: type
  label: type
- type: file
  name: image
  label: image
- type: list
  name: category
  label: category
- type: image_gallery
  name: project_images
  label: project_images
pages:
- content/services/seamless-watch.md
- content/services/use-less-brand.md
